### PR TITLE
Attach permissions before argo provisioning operations

### PR DESCRIPTION
**Pull request by stafot**
#### Summary
Attach permissions before argo provisioning operations

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-7814

#### Release Note

```release-note
Fix nginx failure because of missing permissions
```

### CODE REVIEW

**Review by angeloskyratzakos — APPROVED** [review]

**Review by stylianosrigas — APPROVED** [review]

**Review by stylianosrigas — COMMENTED** [review]
@stafot why not to use the err reference?

**Comment by stafot** [comment]
@stylianosrigas check lint failures and suggestions in previous runs.

**Comment by stafot** [comment]
@stylianosrigas alternatively I could   use   `var err error` . Do you prefer this?

**Comment by gabrieljackson** [comment]
Looks like you still used `err1`. I am 0/5 on how we write this out to avoid shadowing so just let me know if this is what you would like to proceed with.

**Comment by stafot** [comment]
@gabrieljackson fixed

**Review by stylianosrigas — APPROVED** [review]
LGTM

**Review by gabrieljackson — APPROVED** [review]

**Pull request merged**
