### PR TITLE
MM-29237 - Schedule Installations based on Annotations

### PR DESCRIPTION
**Pull request by Szymongib**
#### Summary

This PR makes use of Annotations during the scheduling of Installation to the Cluster.
The filtering of clusters is guided by the following principles:
- Installations can be scheduled on any cluster which contains all Annotations present on the Installation.
- Clusters can contain any additional Annotations not present on the Installation.
- Installation without Annotations can be scheduled on any available cluster.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-29237

#### Release Note

```release-note
Schedule Installations on Clusters based on the Annotations
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
can we have some docs about how to use that?

**Comment by Szymongib** [comment]
> can we have some docs about how to use that?

Yeah, that is a good point. Will the README be sufficient, or is there some better place?

**Comment by cpanato** [comment]
@Szymongib we can create a docs directory and add things there

**Comment by Szymongib** [comment]
@cpanato I have added docs. Please take a look let me know if there is something more you would like to see in them.

**Review by cpanato — APPROVED** [review]

**Review by gabrieljackson — APPROVED** [review]
Great tests and docs!

**Pull request merged**
