### PR TITLE
Update to latest Calico CNI

### PR DESCRIPTION
**Pull request by stafot**
Issue: MM-37444

#### Summary
Update to latest Calico CNI
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37444

#### Release Note

```release-note
Update to latest Calico CNI.
```

### CODE REVIEW

**Review by stylianosrigas — APPROVED** [review]
LGTM

**Review by gabrieljackson — APPROVED** [review]
Awesome!

I am curious what sort of initial testing we have done on this? Just want to check that we have tried this with a new cluster creation as well as an upgrade.

**Review by Mshahidtaj — APPROVED** [review]
LGTM, 
@gabrieljackson we haven't tested it yet with the new cluster but we do have seperate ticket https://mattermost.atlassian.net/browse/MM-37435 to do that.

**Review by Szymongib — APPROVED** [review]
LGTM
To second @gabrieljackson point, should we test locally first?

**Comment by stafot** [comment]
@gabrieljackson @Szymongib  To answer your questions we tested the basic scenarios of cluster creation with calico as CNI and cluster provision of existing cluster with AWS CNI. This PR was a bit urgent as currently we were not able to provision the clusters that use calico CNI as without latest version master nodes failing.

**Pull request merged**
