### PR TITLE
Add job and make to check the outdated modules

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- add a job and make entry to help us to check the outdated modules
- removed the not needed dependency - cert-manager

#### Ticket Link
N/a

#### Release Note

```release-note
add a job and make entry to help us to check the outdated modules
```

### CODE REVIEW

**Comment by cpanato** [comment]
this is the output
```
+-------------------------------------------+----------------+-------------+--------+------------------+
|                  MODULE                   |    VERSION     | NEW VERSION | DIRECT | VALID TIMESTAMPS |
+-------------------------------------------+----------------+-------------+--------+------------------+
| github.com/Masterminds/squirrel           | v1.2.0         | v1.4.0      | true   | true             |
| github.com/aws/aws-sdk-go                 | v1.29.31       | v1.31.0     | true   | true             |
| github.com/golang/mock                    | v1.3.1         | v1.4.3      | true   | true             |
| github.com/lib/pq                         | v1.3.0         | v1.5.2      | true   | true             |
| github.com/mattermost/mattermost-operator | v1.3.0         | v1.4.0      | true   | true             |
| github.com/sirupsen/logrus                | v1.4.2         | v1.6.0      | true   | true             |
| github.com/spf13/cobra                    | v0.0.5         | v1.0.0      | true   | true             |
| k8s.io/api                                | v0.16.7        | v0.18.2     | true   | true             |
| k8s.io/apiextensions-apiserver            | v0.16.7        | v0.18.2     | true   | true             |
| k8s.io/apimachinery                       | v0.16.8-beta.0 | v0.18.2     | true   | true             |
| k8s.io/kube-aggregator                    | v0.16.7        | v0.18.2     | true   | true             |
+-------------------------------------------+----------------+-------------+--------+------------------+
```

**Comment by cpanato** [comment]
i will update the deps in a follow up

/cc @gabrieljackson just FYI

**Comment by gabrieljackson** [comment]
Hey @cpanato, looks nice!

I just wanted to verify something: this job will never fail because our modules are out of date right? I ask because it is unlikely our k8s modules will ever be fully up to date due to how we will want to peg to specific versions.

If this is just for our own info then LGTM!

**Comment by cpanato** [comment]
@gabrieljackson it will not fail, at least should not fail :) this is just to notify us in the job, but you can run locally as well with `make check-modules`

**Pull request merged**
