### PR TITLE
Bump terraform to v0.15.5

### PR DESCRIPTION
**Pull request by stafot**
Signed-off-by: Stavros Foteinopoulos <stafot@gmail.com>

#### Summary
Bump terraform to v0.15.5

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-2351

#### Release Note

```release-note
Bump terraform to v0.15.5
```

### CODE REVIEW

**Review by spirosoik — APPROVED** [review]

**Comment by stafot** [comment]
@gabrieljackson Is required to move with kops 1.22

**Review by Szymongib — APPROVED** [review]

**Review by gabrieljackson — APPROVED** [review]
Looks like tests failed, but the change looks good.

**Comment by stafot** [comment]
@gabrieljackson It fail because I am using a fork. Either I need to raise new PR directly from the parent repo or merge it and let it succeed on master branch. 0/5 for both.

**Comment by gabrieljackson** [comment]
> @gabrieljackson It failed because I am using a fork. Either I need to raise new PR directly from the parent repo or merge it and let it succeed on master branch. 0/5 for both.

Yep, I am 0/5 on it as well so proceed however you like.

**Pull request closed without merging**
