### PR TITLE
Revert command functions to their earlier names

### PR DESCRIPTION
**Pull request by mirshahriar**
#### Summary

Example

`newCmdCluster()` -> `clusterCmd()`

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by fmartingr — APPROVED** [review]
PR itself it's ok, though I like the `newXXX` functions more, since they actually creating objects. The old naming was like that because those were the actual cobra commands, not a factory of them. But I'll leave it up what you think is best. 1/5.

**Comment by mirshahriar** [comment]
> The old naming was like that because those were the actual cobra commands

I completely agree.  These functions are creating new cobra command, so good to have `newCmd` prefix.  But, It is up to @gabrieljackson.

**Review by gabrieljackson — APPROVED** [review]
I see where you guys are coming from on this and am 0/5 now on the names. I will approve and you can decide whether to merge or close the PR. Totally fine with either.

**Comment by mirshahriar** [comment]
Lets keep command name to `newXXX`

**Pull request closed without merging**
