### PR TITLE
[CLD-5436]Add vpcID tag to nginx LB

### PR DESCRIPTION
**Pull request by andrleite**
#### Summary
This change will add VpcID tag to nginx loadbalancers. 

I've tried `cluster.ProvisionerMetadataKops.VPC` but at the moment we update the Nginx service the value for VPC is empty.

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/CLD-5436

#### Release Note

```release-note
none
```

### CODE REVIEW

**Review by stylianosrigas — APPROVED** [review]
LGTM 👍

**Comment by stylianosrigas** [comment]
@andrleite Lets wait for a pair of eyes from platform team ;)

**Comment by gabrieljackson** [comment]
@fmartingr yeah I agree. Let's go ahead and merge this as is and we can do a bit of cleanup on our team. This issue results from us persisting the VPC ID and other metadata at a later step. We can look into storing it earlier and/or more often in the creation flow.

**Comment by mirshahriar** [comment]
> we can persist the data under the PrepareCluster/CreateCluster steps in the provisioner 

You are right. I have done the same thing for EKS.

**Review by mirshahriar — APPROVED** [review]
LGTM

**Pull request merged**
