### PR TITLE
[MM 31037] Updating utility default values to meet dev requirements.

### PR DESCRIPTION
**Pull request by stylianosrigas**
#### Summary
- Updating utility default values to meet dev requirements.

With these changes a cluster of two nodes is enough to accommodate utilities and a small 100user installation. The rest of the environments are getting utility values from the remote git repo. 

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-31037

#### Release Note
```release-note
- Updating utility default values to meet dev requirements.
```

### CODE REVIEW

**Review by angeloskyratzakos — APPROVED** [review]
LGTM

**Review by gabrieljackson — COMMENTED** [review]
Did you mean to add `cloud.db-journal` to this commit? Looks like it may be unrelated.

**Comment by stylianosrigas** [comment]
> Did you mean to add `cloud.db-journal` to this commit? Looks like it may be unrelated.

Oops totally right. Removed, thanks <3

**Review by gabrieljackson — APPROVED** [review]
Thanks for this. My poor dev cluster was freaking out a a bit. ;)

**Pull request merged**
