### PR TITLE
Update kops to 1.13.0

### PR DESCRIPTION
**Pull request by gabrieljackson**
This allows us to deploy kubernetes 1.13.X clusters!

### CODE REVIEW

**Comment by cpanato** [comment]
i was about to do that 😂

**Comment by cpanato** [comment]
@gabrieljackson can we use the cluster provision command to upgrade the k8s cluster?

**Comment by gabrieljackson** [comment]
The provision command is for updating the operators and other kubernetes objects. This will require running `cloud cluster upgrade` to specifically handle upgrading k8s.

A note here: we haven't been able to test this much so far so we should perform some tests on throwaway clusters first.

**Comment by cpanato** [comment]
will do after we merge this :)

**Pull request merged**
